// US Airport Database - Top airports with metadata for wait time simulation
const AIRPORTS = [
    { code: "ATL", name: "Hartsfield-Jackson Atlanta International", city: "Atlanta, GA", size: "mega", timezone: "America/New_York" },
    { code: "LAX", name: "Los Angeles International", city: "Los Angeles, CA", size: "mega", timezone: "America/Los_Angeles" },
    { code: "ORD", name: "O'Hare International", city: "Chicago, IL", size: "mega", timezone: "America/Chicago" },
    { code: "DFW", name: "Dallas/Fort Worth International", city: "Dallas, TX", size: "mega", timezone: "America/Chicago" },
    { code: "DEN", name: "Denver International", city: "Denver, CO", size: "mega", timezone: "America/Denver" },
    { code: "JFK", name: "John F. Kennedy International", city: "New York, NY", size: "mega", timezone: "America/New_York" },
    { code: "SFO", name: "San Francisco International", city: "San Francisco, CA", size: "mega", timezone: "America/Los_Angeles" },
    { code: "SEA", name: "Seattle-Tacoma International", city: "Seattle, WA", size: "large", timezone: "America/Los_Angeles" },
    { code: "LAS", name: "Harry Reid International", city: "Las Vegas, NV", size: "large", timezone: "America/Los_Angeles" },
    { code: "MCO", name: "Orlando International", city: "Orlando, FL", size: "large", timezone: "America/New_York" },
    { code: "EWR", name: "Newark Liberty International", city: "Newark, NJ", size: "large", timezone: "America/New_York" },
    { code: "CLT", name: "Charlotte Douglas International", city: "Charlotte, NC", size: "large", timezone: "America/New_York" },
    { code: "PHX", name: "Phoenix Sky Harbor International", city: "Phoenix, AZ", size: "large", timezone: "America/Phoenix" },
    { code: "IAH", name: "George Bush Intercontinental", city: "Houston, TX", size: "large", timezone: "America/Chicago" },
    { code: "MIA", name: "Miami International", city: "Miami, FL", size: "large", timezone: "America/New_York" },
    { code: "BOS", name: "Boston Logan International", city: "Boston, MA", size: "large", timezone: "America/New_York" },
    { code: "MSP", name: "Minneapolis-Saint Paul International", city: "Minneapolis, MN", size: "large", timezone: "America/Chicago" },
    { code: "DTW", name: "Detroit Metropolitan Wayne County", city: "Detroit, MI", size: "large", timezone: "America/Detroit" },
    { code: "FLL", name: "Fort Lauderdale-Hollywood International", city: "Fort Lauderdale, FL", size: "large", timezone: "America/New_York" },
    { code: "PHL", name: "Philadelphia International", city: "Philadelphia, PA", size: "large", timezone: "America/New_York" },
    { code: "LGA", name: "LaGuardia", city: "New York, NY", size: "large", timezone: "America/New_York" },
    { code: "BWI", name: "Baltimore/Washington International", city: "Baltimore, MD", size: "large", timezone: "America/New_York" },
    { code: "SLC", name: "Salt Lake City International", city: "Salt Lake City, UT", size: "large", timezone: "America/Denver" },
    { code: "DCA", name: "Ronald Reagan Washington National", city: "Washington, DC", size: "large", timezone: "America/New_York" },
    { code: "IAD", name: "Washington Dulles International", city: "Washington, DC", size: "large", timezone: "America/New_York" },
    { code: "SAN", name: "San Diego International", city: "San Diego, CA", size: "medium", timezone: "America/Los_Angeles" },
    { code: "TPA", name: "Tampa International", city: "Tampa, FL", size: "medium", timezone: "America/New_York" },
    { code: "PDX", name: "Portland International", city: "Portland, OR", size: "medium", timezone: "America/Los_Angeles" },
    { code: "HNL", name: "Daniel K. Inouye International", city: "Honolulu, HI", size: "medium", timezone: "Pacific/Honolulu" },
    { code: "STL", name: "St. Louis Lambert International", city: "St. Louis, MO", size: "medium", timezone: "America/Chicago" },
    { code: "BNA", name: "Nashville International", city: "Nashville, TN", size: "medium", timezone: "America/Chicago" },
    { code: "AUS", name: "Austin-Bergstrom International", city: "Austin, TX", size: "medium", timezone: "America/Chicago" },
    { code: "HOU", name: "William P. Hobby", city: "Houston, TX", size: "medium", timezone: "America/Chicago" },
    { code: "OAK", name: "Oakland International", city: "Oakland, CA", size: "medium", timezone: "America/Los_Angeles" },
    { code: "MSY", name: "Louis Armstrong New Orleans International", city: "New Orleans, LA", size: "medium", timezone: "America/Chicago" },
    { code: "SJC", name: "San Jose International", city: "San Jose, CA", size: "medium", timezone: "America/Los_Angeles" },
    { code: "SMF", name: "Sacramento International", city: "Sacramento, CA", size: "medium", timezone: "America/Los_Angeles" },
    { code: "RDU", name: "Raleigh-Durham International", city: "Raleigh, NC", size: "medium", timezone: "America/New_York" },
    { code: "CLE", name: "Cleveland Hopkins International", city: "Cleveland, OH", size: "medium", timezone: "America/New_York" },
    { code: "IND", name: "Indianapolis International", city: "Indianapolis, IN", size: "medium", timezone: "America/Indiana/Indianapolis" },
    { code: "PIT", name: "Pittsburgh International", city: "Pittsburgh, PA", size: "medium", timezone: "America/New_York" },
    { code: "CMH", name: "John Glenn Columbus International", city: "Columbus, OH", size: "medium", timezone: "America/New_York" },
    { code: "MCI", name: "Kansas City International", city: "Kansas City, MO", size: "medium", timezone: "America/Chicago" },
    { code: "SAT", name: "San Antonio International", city: "San Antonio, TX", size: "medium", timezone: "America/Chicago" },
    { code: "SNA", name: "John Wayne (Orange County)", city: "Santa Ana, CA", size: "medium", timezone: "America/Los_Angeles" },
    { code: "MKE", name: "Milwaukee Mitchell International", city: "Milwaukee, WI", size: "medium", timezone: "America/Chicago" },
    { code: "JAX", name: "Jacksonville International", city: "Jacksonville, FL", size: "medium", timezone: "America/New_York" },
    { code: "ABQ", name: "Albuquerque International Sunport", city: "Albuquerque, NM", size: "small", timezone: "America/Denver" },
    { code: "OMA", name: "Eppley Airfield", city: "Omaha, NE", size: "small", timezone: "America/Chicago" },
    { code: "BUR", name: "Hollywood Burbank", city: "Burbank, CA", size: "small", timezone: "America/Los_Angeles" },
    { code: "RIC", name: "Richmond International", city: "Richmond, VA", size: "small", timezone: "America/New_York" },
    { code: "BDL", name: "Bradley International", city: "Hartford, CT", size: "small", timezone: "America/New_York" },
    { code: "OKC", name: "Will Rogers World", city: "Oklahoma City, OK", size: "small", timezone: "America/Chicago" },
    { code: "BUF", name: "Buffalo Niagara International", city: "Buffalo, NY", size: "small", timezone: "America/New_York" },
    { code: "RNO", name: "Reno-Tahoe International", city: "Reno, NV", size: "small", timezone: "America/Los_Angeles" },
    { code: "TUS", name: "Tucson International", city: "Tucson, AZ", size: "small", timezone: "America/Phoenix" },
    { code: "ONT", name: "Ontario International", city: "Ontario, CA", size: "small", timezone: "America/Los_Angeles" },
    { code: "PBI", name: "Palm Beach International", city: "West Palm Beach, FL", size: "small", timezone: "America/New_York" },
    { code: "RSW", name: "Southwest Florida International", city: "Fort Myers, FL", size: "small", timezone: "America/New_York" },
    { code: "SDF", name: "Louisville Muhammad Ali International", city: "Louisville, KY", size: "small", timezone: "America/Kentucky/Louisville" },
    { code: "ORF", name: "Norfolk International", city: "Norfolk, VA", size: "small", timezone: "America/New_York" },
    { code: "BOI", name: "Boise Airport", city: "Boise, ID", size: "small", timezone: "America/Boise" },
    { code: "GEG", name: "Spokane International", city: "Spokane, WA", size: "small", timezone: "America/Los_Angeles" },
    { code: "ELP", name: "El Paso International", city: "El Paso, TX", size: "small", timezone: "America/Denver" },
    { code: "MDW", name: "Chicago Midway International", city: "Chicago, IL", size: "medium", timezone: "America/Chicago" },
    { code: "DAL", name: "Dallas Love Field", city: "Dallas, TX", size: "medium", timezone: "America/Chicago" },
    { code: "CHS", name: "Charleston International", city: "Charleston, SC", size: "small", timezone: "America/New_York" },
    { code: "ALB", name: "Albany International", city: "Albany, NY", size: "small", timezone: "America/New_York" },
    { code: "DSM", name: "Des Moines International", city: "Des Moines, IA", size: "small", timezone: "America/Chicago" },
    { code: "LIT", name: "Bill and Hillary Clinton National", city: "Little Rock, AR", size: "small", timezone: "America/Chicago" },
    { code: "GRR", name: "Gerald R. Ford International", city: "Grand Rapids, MI", size: "small", timezone: "America/Detroit" },
    { code: "SYR", name: "Syracuse Hancock International", city: "Syracuse, NY", size: "small", timezone: "America/New_York" },
    { code: "TUL", name: "Tulsa International", city: "Tulsa, OK", size: "small", timezone: "America/Chicago" },
    { code: "PWM", name: "Portland International Jetport", city: "Portland, ME", size: "small", timezone: "America/New_York" },
    { code: "MEM", name: "Memphis International", city: "Memphis, TN", size: "small", timezone: "America/Chicago" },
    { code: "ANC", name: "Ted Stevens Anchorage International", city: "Anchorage, AK", size: "small", timezone: "America/Anchorage" },
    { code: "BHM", name: "Birmingham-Shuttlesworth International", city: "Birmingham, AL", size: "small", timezone: "America/Chicago" },
    { code: "ROC", name: "Frederick Douglass Greater Rochester International", city: "Rochester, NY", size: "small", timezone: "America/New_York" },
    { code: "GSP", name: "Greenville-Spartanburg International", city: "Greenville, SC", size: "small", timezone: "America/New_York" },
    { code: "PVD", name: "Rhode Island T.F. Green International", city: "Providence, RI", size: "small", timezone: "America/New_York" },
    { code: "MSN", name: "Dane County Regional", city: "Madison, WI", size: "small", timezone: "America/Chicago" },
    { code: "DAY", name: "James M. Cox Dayton International", city: "Dayton, OH", size: "small", timezone: "America/New_York" },
    { code: "SAV", name: "Savannah/Hilton Head International", city: "Savannah, GA", size: "small", timezone: "America/New_York" },
    { code: "ICT", name: "Wichita Dwight D. Eisenhower National", city: "Wichita, KS", size: "small", timezone: "America/Chicago" },
    { code: "MYR", name: "Myrtle Beach International", city: "Myrtle Beach, SC", size: "small", timezone: "America/New_York" },
    { code: "XNA", name: "Northwest Arkansas National", city: "Fayetteville, AR", size: "small", timezone: "America/Chicago" },
    { code: "HSV", name: "Huntsville International", city: "Huntsville, AL", size: "small", timezone: "America/Chicago" },
    { code: "LEX", name: "Blue Grass Airport", city: "Lexington, KY", size: "small", timezone: "America/Kentucky/Louisville" },
    { code: "SRQ", name: "Sarasota Bradenton International", city: "Sarasota, FL", size: "small", timezone: "America/New_York" },
    { code: "FAT", name: "Fresno Yosemite International", city: "Fresno, CA", size: "small", timezone: "America/Los_Angeles" },
    { code: "GSO", name: "Piedmont Triad International", city: "Greensboro, NC", size: "small", timezone: "America/New_York" },
    { code: "CAK", name: "Akron-Canton", city: "Akron, OH", size: "small", timezone: "America/New_York" },
    { code: "MAF", name: "Midland International Air and Space Port", city: "Midland, TX", size: "small", timezone: "America/Chicago" },
    { code: "FNT", name: "Bishop International", city: "Flint, MI", size: "small", timezone: "America/Detroit" },
    { code: "AVL", name: "Asheville Regional", city: "Asheville, NC", size: "small", timezone: "America/New_York" },
    { code: "PSP", name: "Palm Springs International", city: "Palm Springs, CA", size: "small", timezone: "America/Los_Angeles" },
    { code: "COS", name: "Colorado Springs", city: "Colorado Springs, CO", size: "small", timezone: "America/Denver" },
    { code: "FSD", name: "Sioux Falls Regional", city: "Sioux Falls, SD", size: "small", timezone: "America/Chicago" },
    { code: "MLI", name: "Quad City International", city: "Moline, IL", size: "small", timezone: "America/Chicago" },
];

// Popular airports shown on tracker home
const POPULAR_AIRPORTS = ["ATL", "LAX", "JFK", "ORD", "DFW", "DEN", "SFO", "SEA", "MIA", "LAS", "BOS", "MCO"];
